name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # или другая ветка, в которую происходит деплой

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # - name: Install dependencies
      # run: npm install # если у вас есть зависимости

    - name: Replace form action URL
      run: |
        sed -i 's|action=""|action="https://formspree.io/f/xgvwpabp"|' path/to/your/index.html

    # - name: Build project
      # run: npm run build # если у вас есть процесс сборки, иначе пропустите этот шаг

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # путь к вашей сборке или корневой папке сайта
